# Generated by Django 3.2.3 on 2021-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glucose', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucose',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='glucose',
            index=models.Index(fields=['date_time'], name='glucose_glu_date_ti_4feef8_idx'),
        ),
    ]
