# Generated by Django 3.2.3 on 2021-06-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glucose', '0002_auto_20210615_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucose',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='glucose',
            name='glucose_glu_date_ti_4feef8_idx',
        ),
    ]
