# Generated by Django 3.2.3 on 2021-06-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_alter_temperature_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='temperature',
            index=models.Index(fields=['date_time'], name='temperature_date_ti_abeb5c_idx'),
        ),
    ]
